--- #YAML:1.0
name:                Math-Random-SkewNormal
version:             0.03
abstract:            Random numbers following a SkewNormal PDF
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jiri Vaclavik <my name dot my surname at gmail dot com>
